app2/lotto/urls.py
from django.conf.urls import url
from . import views

app_name = 'lotto'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new/$', views.post, name = "new_lotto"),
    url(r'^(?P<lottokey>[0-9]+)/detail/$', views.detail, name='detail'),
]

app2/lotto/models.py
from django.db import models

from django.utils import timezone
import random
# Create your models here.
class GuessNumbers(models.Model):
    name = models.CharField(max_length = 24)
    lottos = models.CharField(max_length = 255, default = '[1,2,3,4,5,6]')
    text = models.CharField(max_length = 255)
    num_lotto = models.IntegerField(default = 5)
    update_date = models.DateTimeField()

    # 로또 번호 생성 및 데이터베이스 저장
    def generate(self):
        self.lottos = ""
        origin = list(range(1,46))
        for _ in range(0, self.num_lotto):
            random.shuffle(origin)
            guess = origin[:6]
            guess.sort()
            self.lottos += str(guess) +'\n'
        self.update_date = timezone.now()
        self.save()

    def __str__(self):
        return "%s %s" % (self.name, self.text)

app2/lotto/forms.py
from django import forms
from .models import GuessNumbers

class PostForm(forms.ModelForm):

    class Meta:
        model = GuessNumbers
        fields = ('name', 'text',)

app2/lotto/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

# Create your views here.
from .models import GuessNumbers
from .forms import PostForm

def index(request):
    lottos = GuessNumbers.objects.all()
    return render(request, "lotto/default.html", {"lottos": lottos})

def post(request):
    if request.method == "POST":
        # save data
        form = PostForm(request.POST)
        if form.is_valid():
            lotto = form.save(commit = False)
            lotto.generate()
            return redirect('lotto:index')
    else:
        form = PostForm()
        return render(request, 'lotto/form.html', {"form": form})

def detail(request, lottokey):
    lotto = GuessNumbers.objects.get(pk = lottokey)
    return render(request, "lotto/detail.html", {"lotto": lotto})

app2/lotto/templates/lotto/default.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ko">
<head>
  <title>My Little Lotto</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link href="//fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/lotto.css'%}">
</head>

<body>
  <div class="page-header">
  <h1>My Lotto Page</h1>
  <h2> <a href="{% url 'lotto:new_lotto'%}">
    <span class="glyphicon glyphicon-plus btn btn-default"></span></a></h2>
  </div>
  <div class="container lotto">
    {% for lotto in lottos %}
    <h2><a href="{% url 'lotto:detail' lottokey=lotto.pk %}">{{lotto.text}}</a></h2>
    <p> {{lotto.update_date}}</p>
    <p> {{lotto.lottos|linebreaksbr}}</p>
    {% endfor %}
  </div>
</body>
</html>

app2/lotto/templates/lotto/detail.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ko">
<head>
  <title>My Little Lotto</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link href="//fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/lotto.css'%}">
</head>

<body>
  <div class="page-header">
  <h1>My Lotto Page</h1>
  </div>
  <div class="container lotto">
    <h2>{{lotto.text}}</h2>
    <p> by {{lotto.name}}</p>
    <p> {{lotto.update_date}}</p>
    <p> {{lotto.lottos|linebreaksbr}}</p>
  </div>
</body>
</html>

app2/lotto/templates/lotto/form.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ko">
<head>
  <title>My Little Lotto</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link href="//fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/lotto.css' %}">
</head>

<body>
  <div class="page-header">
  <h1>My Little New Lotto</h1>
  </div>
  <div class="container lotto">
    <form method="POST" class="post-form">
      {%csrf_token%}
      {{form.as_p}}
      <button type="submit" class="save btn btn-default">Save</button>
    </form>
  </div>
</body>
</html>